DROP TABLE IF EXISTS fare_data_cleaned
;

CREATE TABLE fare_data_cleaned (
    FULL_CODE TEXT(22),
    FLOW_ID TEXT(7),
    TICKET_CODE TEXT(3),
    FARE TEXT(8),
    RESTRICTION_CODE TEXT(2)
);

INSERT INTO fare_data_cleaned (FULL_CODE,FLOW_ID,TICKET_CODE,FARE,RESTRICTION_CODE)
SELECT DISTINCT
    FULL_CODE,
    FLOW_ID,
    TICKET_CODE,
    FARE,
    RESTRICTION_CODE
FROM fare_data_20230829
;
