CREATE TABLE fare_data_cleaned
AS
SELECT
    FULL_CODE,
    FLOW_ID,
    TICKET_CODE,
    FARE,
    RESTRICTION_CODE
FROM
(
    SELECT
        FULL_CODE,
        FLOW_ID,
        TICKET_CODE,
        FARE,
        RESTRICTION_CODE,
        ROW_NUMBER() OVER(PARTITION BY FULL_CODE, FLOW_ID, TICKET_CODE, FARE, RESTRICTION_CODE) AS rn
    FROM fare_data_20230829
) T
WHERE rn=1